version: '3'
services:
  uptasticsearch:
    build: .
    depends_on:
      - "es_1"
      - "es_2"
      - "es_5"
      - "es_6"
  es_1:
    image: "elasticsearch:1.7"
  es_2:
    image: "elasticsearch:2.4.6"
  es_5:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.4.3"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
  es_6:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.1.1"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
